### ISSUE TITLE
Travis is broken

### ISSUE THREAD

**Issue by khoek** [semorrison/lean-tidy#11]
:(, some problem with the stdlibc++ version available in travis?

**Comment by kim-em** [comment]
Do you know what's going on here? Presumably this is caused by khoek/klean having different library dependencies than standard lean?

**Comment by khoek** [comment]
I didn't realise this... yeah. I'll try recompiling with gcc-4.8 and see if it works then.

**Comment by khoek** [comment]
This is solved in https://github.com/khoek/lean-tidy/commit/3ba750e3f7a9b60a2f814e2cdca343e13143fd3c.

I tried really hard to build `klean` with `gcc-4.9` (which is the minimum for lean), but my system libs keps leaking through. Instead we just upgrade travis to something a little less ancient.

**Comment by khoek** [comment]
"launchpadlibrarian.net" might look a bit dodge but its actually the official domain which the binaries for launchpad.net are hosted, which are the official packages for Ubuntu.

**Comment by khoek** [comment]
The "principled" solution to fixing travis this way, instead of the binary, would be to change the apt repository sources in travis and properly ask apt to fetch things (so we don't have to provide dependencies and the like). But I think that would make travis fetch a tremendous number of packages and essentially upgrade its ubuntu version to the next release (it has to do this for all of its package versions to be consistent), which would make builds take a lot longer (maybe they would fail?)

**Comment by khoek** [comment]
My current understanding is that "official lean" doesn't have this problem by luck: travis uses gcc-4.8 stuff and lean requires at least gcc-4.9 to build (at least thats what it says in the CMake files), but it is linked statically. I tried to do this on my computer too (with `-DSTATIC=ON` plus the compiler version flags) as a last resort, but gcc emits a binary which segfaults, and I didn't want to start debugging the assembly

**Comment by khoek** [comment]
I messed around with the `klean` github release without changing the version number while trying to fix this, so please clear the travis build cache at travis-ci.org (under More Options -> Caches)

**Comment by kim-em** [comment]
Done.
