### ISSUE TITLE
Regression in rewrite_all

### ISSUE THREAD

**Issue by khoek** [semorrison/lean-tidy#6]
Commit d2812dab59e9ab317dd7bfd95cbb475af66fce38 on master broke rewrite_all so that many rewrites in https://github.com/semorrison/lean-category-theory get missed.

6a2d7f61957151b27ea41dc783e497d62c2c0a7b is safe.

**Comment by kim-em** [comment]
Sorry about that. A later commit seems to have fixed everything.

**Comment by kim-em** [comment]
Oh, sorry, rubbish, I hadn't run `leanpkg upgrade`. I'm off to dinner, and will try to fix my idiocy after that.

**Comment by kim-em** [comment]
ae9de6aa212eb33311373d44e441edc7ee04a231 fixes this bug. Close #6.
